#!/bin/bash -xe

driver=${DOCKER_MACHINE_DRIVER:-"virtualbox"} ## TODO: validate if this is not a cloud-based driver, as those work work with this

docker_machine_create() {
  for vm in $@ ; do
    docker-machine create --driver ${driver} "${vm}"
  done
}

weave_launch() {
  for vm in $@ ; do
    env DOCKER_CLIENT_ARGS="$(docker-machine config ${vm})" \
      weave launch $(docker-machine ip $@)
  done
  for vm in $@ ; do
    env DOCKER_CLIENT_ARGS="$(docker-machine config ${vm})" \
      weave expose -h "${vm}.weave.local"
  done
}

osx_setup_commands() {
  export DOCKER_CLIENT_ARGS="$(docker-machine config $1)"
  weave_ipam_default_subnet=$(weave report -f "{{.IPAM.DefaultSubnet}}")
  weave_dns_domain=$(weave report -f "{{.DNS.Domain}}" | sed "s/^\(.*\)\.$/\1/")
  vm_ip=$(docker-machine ip $1)
  unset DOCKER_CLIENT_ARGS
  echo "sudo route add -net ${weave_ipam_default_subnet} ${vm_ip}"
  echo "sudo mkdir /etc/resolver/"
  echo "echo nameserver ${vm_ip} | sudo tee /etc/resolver/${weave_dns_domain}"
}

head_node() {
  echo $1
}

## TODO: creation should be an opt-in

number_of_vms=$1 ## TODO: validate if this is a number and it's greater then 1

vm_name_prefix=${VM_NAME_PREFIX:-"weave-${driver}"}

vms=$(seq -f "${vm_name_prefix}-%g" $number_of_vms)

docker_machine_create $vms

weave_launch $vms

osx_setup_commands $(head_node $vms)
